# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preview.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 100, 600, 60))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Pre_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Pre_pushButton.setGeometry(QtCore.QRect(625, 100, 150, 60))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.Pre_pushButton.setFont(font)
        self.Pre_pushButton.setObjectName("Pre_pushButton")
        self.Pre_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.Pre_listWidget.setGeometry(QtCore.QRect(30, 180, 501, 121))
        self.Pre_listWidget.setObjectName("Pre_listWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.Pre_pushButton.clicked.connect(MainWindow.getfile)  # type: ignore
        self.Pre_listWidget.itemClicked['QListWidgetItem*'].connect(MainWindow.itemClick)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "请选择预览的图片，点击下方图片名称即可预览"))
        self.Pre_pushButton.setText(_translate("MainWindow", "选择图片"))
