# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rename.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QCoreApplication

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Re_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Re_pushButton.setGeometry(QtCore.QRect(400, 30, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.Re_pushButton.setFont(font)
        self.Re_pushButton.setObjectName("Re_pushButton")
        self.Old_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.Old_listWidget.setGeometry(QtCore.QRect(20, 180, 450, 150))
        self.Old_listWidget.setObjectName("Old_listWidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 360, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(20, 400, 450, 150))
        self.listWidget_2.setObjectName("listWidget_2")
        self.Re_pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Re_pushButton_2.setGeometry(QtCore.QRect(400, 340, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.Re_pushButton_2.setFont(font)
        self.Re_pushButton_2.setObjectName("Re_pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 90, 451, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.Re_pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Re_pushButton_3.setGeometry(QtCore.QRect(20, 570, 451, 45))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.Re_pushButton_3.setFont(font)
        self.Re_pushButton_3.setObjectName("Re_pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Re_pushButton.clicked.connect(MainWindow.getfile)  # type: ignore
        self.Re_pushButton_2.clicked.connect(MainWindow.Rename)  # type: ignore
        self.Re_pushButton_3.clicked.connect(MainWindow.Back)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "点击选择重命名的文件夹"))
        self.Re_pushButton.setText(_translate("MainWindow", "选择"))
        self.label_2.setText(_translate("MainWindow", "待命名文件如下所示："))
        self.label_3.setText(_translate("MainWindow", "重命名后如下所示："))
        self.Re_pushButton_2.setText(_translate("MainWindow", "重命名"))
        self.Re_pushButton_3.setText(_translate("MainWindow", "保存"))
